### ISSUE TITLE
import problem on windows

### ISSUE THREAD

**Issue by skaffen2** [ajhager/engi#18] opened 2015-03-16 22:18 UTC
Hi,

I haven't really seen much doco around about these import paths, but I'm having a problem with go version go1.4 windows/amd64.  I didn't have a problem with go1.3 on a different windows 64 bit machine.  I had the azul3d demos working ok on this machine, but engi doesn't install for some reason.

C:\Users\kx\go\src>go get -u github.com/ajhager/engi
package github.com/ajhager/engi
        imports azul3d.org/native/glfw.v4
        imports github.com/ajhager/webgl
        imports github.com/go-gl/glow/gl/2.1/gl
        imports github.com/go-gl/glow/gl/2.1/gl
        imports github.com/go-gl/glow/gl/2.1/gl: code in directory C:\Users\kx\go\src\github.com\go-gl\glow\gl\2.1\gl expects
import "github.com/go-gl/gl/v2.1/gl"

**Comment by shurcooL** [comment] 2015-03-16 22:23
Hey @skaffen2,

The problem is in github.com/ajhager/webgl package, it currently uses import paths that are in need of updating. Namely, it imports `github.com/go-gl/glow/gl/2.1/gl` but that import path has changed to `github.com/go-gl/gl/v2.1/gl`.

**Comment by shurcooL** [comment] 2015-03-17 07:06
@skaffen2, I've fixed the import path issue in the `github.com/ajhager/webgl` dependency.

Can you try `go get -u github.com/ajhager/engi` again and see if the issue is fixed please?

**Comment by skaffen2** [comment] 2015-03-17 08:49
@shurcooL thanks that fixes the issue.

**Comment by shurcooL** [comment] 2015-03-18 04:38
Glad to hear it! :)

You can close this issue since it's resolved.

**Comment by ajhager** [comment] 2015-03-18 05:03
Thanks @skaffen2 and @shurcooL !

**Closed by ajhager** 2015-03-18 05:03 UTC
